# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
default:
  # All jobs are interruptible by default
  interruptible: true

variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-frontend

stages:
  - sync
  - lint
  - build
  - release
  - deploy

# Conditions
############
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'


# Workflow
##########
workflow:
  rules:
    - <<: *if-tag
    - <<: *if-default-branch-refs
    - <<: *if-merge-request


include:
  - project: labs/salt-automation
    file:
      - gitlab-ci-templates/common/conventional-commits.v1.yml
      - gitlab-ci-templates/common/docker-build-meta.v1.yml
      - gitlab-ci-templates/common/docker-release.v1.yml
      - gitlab-ci-templates/common/config-updater-meta.v1.yml
  - project: labs/salt-automation
    file: gitlab-ci-templates/common/pre-commit.v1.yml
    rules:
      - <<: *if-merge-request


# Sync stage
############
Do not interrupt:
  stage: sync
  image: alpine:latest
  interruptible: false
  variables:
    GIT_STRATEGY: none
  script:
    - echo "This jobs makes sure this pipeline won't be interrupted!"
    - echo "It works because you cannot cancel subsequent jobs after a job with interruptible=false starts."
    - echo "See https://docs.gitlab.com/ee/ci/yaml/#interruptible for more information."
  rules:
    - when: manual
      allow_failure: true


# Build
#######
Build:
  extends:
    - .build-docker
  variables:
    CI_IMAGE: ${IMAGE_SHA}
    BUILD_DOCKER_EXTRA_FLAGS: --build-arg=COMMIT_SHA=${CI_COMMIT_SHA} --build-arg=COMMIT_TAG=${CI_COMMIT_TAG}


# Deploy
########
# Flux
Deploy to Flux Dev:
  extends: .release-to-dev
  needs:
    - Release version
  variables:
    ENDPOINT: os2mo/flux/os2mo-frontend/update-dev

Deploy to Flux Test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/flux/os2mo-frontend/update-test

Deploy to Flux Prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/flux/os2mo-frontend/update-prod

# Salt
Deploy to Salt Dev:
  extends: .release-to-dev
  needs:
    - Release version
  variables:
    ENDPOINT: os2mo/salt/os2mo-frontend/update-dev

Deploy to Salt Test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/salt/os2mo-frontend/update-test

Deploy to Salt Prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/salt/os2mo-frontend/update-prod
